### ISSUE TITLE
Allow expanded file select text in text_misc.yml

### ISSUE THREAD

**Issue by kiij** [kiij/CoilSnake#103]
How to do this, from H.S:

```
    ROM[0xC1F08C] = ASMLoadAddress0E (Continue)
    ROM[0xC1F0C5] = ASMLoadAddress0E (Copy)
    ROM[0xC1F102] = ASMLoadAddress0E (Delete)
    ROM[0xC1F120] = ASMLoadAddress0E (SetUp)
     
    // Copy horizontal alignment
    ROM[0xC1F0DC] = LDX_i (0x0006)
     
    // Delete horizontal alignment
    ROM[0xC1F117] = LDX_i (0x000A)
     
    // Set Up horizontal alignment
    ROM[0xC1F135] = LDX_i (0x000F)
     
    Continue:
    "Continue[00]"
     
    Copy:
    "Copy[00]"
     
    Delete:
    "Delete[00]"
     
    SetUp:
    "Set Up[00]"
```

**Comment by kiij** [comment]
The maximum length for each string is 25 and they do not have to be null terminated

**Comment by HS39** [comment]
ROM[0xC1F08C] = ASMLoadAddress0E (Continue)
ROM[0xC1F0C5] = ASMLoadAddress0E (Copy)
ROM[0xC1F102] = ASMLoadAddress0E (Delete)
ROM[0xC1F120] = ASMLoadAddress0E (SetUp)

// Copy vertical alignment
ROM[0xC1F0D9] = LDY_i (0x0000)

// Copy horizontal alignment
ROM[0xC1F0DC] = LDX_i (0x0006)

// Delete vertical alignment
ROM[0xC1F114] = LDY_i (0x0000)

// Delete horizontal alignment
ROM[0xC1F117] = LDX_i (0x000A)

// Set Up vertical alignment
ROM[0xC1F132] = LDY_i (0x0000)

// Set Up horizontal alignment
ROM[0xC1F135] = LDX_i (0x000F)

Continue:
"Continue[00]"

Copy:
"Copy[00]"

Delete:
"Delete[00]"

SetUp:
"Set Up[00]"
