### ISSUE TITLE
Sprite group #001 is using an incorrect pallete

### ISSUE THREAD

**Issue by Strongbadhomestar1** [kiij/CoilSnake#112]
I redid the Ness sprite for fun to see how it'd turn out in Gimp. When i tried to recompile it, I was hit with this message even though I'm using the same colors the Ness palette would normally use, just in different places. I did see that Gimp had problems with the latest version, so could it be because im using Gimp? or is there something I'm doing incorrectly? I am rather new at this so i figure its my own stupidity hahaha!

**Comment by kiij** [comment]
could you attach the png so I can check?

**Comment by Strongbadhomestar1** [comment]
![001](https://cloud.githubusercontent.com/assets/16889948/12571679/6970dd5a-c3b1-11e5-95b3-59e719a0e774.jpg)

Thanks friend!

**Comment by kiij** [comment]
Yeah, Gimp tends to screw up palettes like this. I suggest using GraphicsGale instead as some people seem to have had success with that program.

**Comment by Strongbadhomestar1** [comment]
Alrighty, thanks a bundle!
